allowBuilds:
  '@apollo/protobufjs': true
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  prisma: true
  unrs-resolver: true
  yarn: true
onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - prisma
  - unrs-resolver
  - yarn
